tasks:
  - name: Init activegate workspace
    before: |
      dd if=/dev/urandom bs=1M count=200 | base64 -w 0
      echo 11111
    init: |
      dd if=/dev/urandom bs=1M count=200 | base64 -w 0
      echo 22222
